config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/generate_csv.rb
module GenerateCsv extend ActiveSupport::Concern
require 'csv'
class_methods do
	def to_csv(collection)
		CSV.generate(col_sep: ";") do |csv|
		  # csv << column_name
          csv << attribute_names
          collection.find_each do |record|
          	csv << record.attributes.values
          end
		end
	end
end
end

app/models/post.rb
class Post < ApplicationRecord
	include GenerateCsv
end

app/models/user.rb
class User < ApplicationRecord
	include GenerateCsv
	#   require 'csv'
	# def self.to_csv(collection)
	# 	CSV.generate(col_sep: ";") do |csv|
	# 	  # csv << column_name
 #          csv << attribute_names
 #          collection.find_each do |record|
 #          	csv << record.attributes.values
 #          end
	# 	end
	# end

	validates :username,:email,:identifier,:first_name,:last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_data Post.to_csv(@posts), filename: Date.today.to_s, content_type: 'text/csv'
      end
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[ show edit update destroy ]
  

  # GET /users or /users.json
  def index
    @users = User.order(created_at: :desc)

    respond_to do |format|
      format.html
      format.csv do |csv|
        send_data User.to_csv(@users), filename: Date.today.to_s, content_type: "text/csv"
      end
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    # headers = ["Username", "Login email", "Identifier", "First name", "Last name"]

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  def import
    file = params[:file]
    return redirect_to users_path, notice: "Only csv please" unless file.content_type == "text/csv"
   
    CsvImportUsersService.new.call(file)

    redirect_to users_path, notice: "Users Imported!!!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :identifier, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Experiment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<%= link_to "Download as CSV", posts_path(format: :csv)%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user,local: false) do |form| %>
   <div class="modal-body">
     
     <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Username %>
    <%= form.text_field :username,class: "form-control mt-3" %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email,class: "form-control mt-3" %>
  </div>

  <div class="field">
    <%= form.label :Identifier %>
    <%= form.text_field :identifier ,class: "form-control mt-3" %>
  </div>

    <div class="field">
    <%= form.label :FirstName %>
    <%= form.text_field :first_name ,class: "form-control mt-3" %>
  </div>

    <div class="field">
    <%= form.label :LastName %>
    <%= form.text_field :last_name ,class: "form-control" %>
  </div>
      </div>
      <div class="modal-footer">

         <%= form.submit class: "btn btn-primary" %>
        <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>

      </div>  
<% end %>

app/views/users/_show.html.erb
<div class="modal-body">
      <div class="col-lg-12">
      <p>
        <strong>UserName:</strong>
        <%= user.username %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= user.email %>
      </p>

      <p>
        <strong>Identifier:</strong>
        <%= user.identifier %>
      </p>

      <p>
        <strong>FirstName:</strong>
        <%= user.first_name %>
      </p>

      <p>
        <strong>LastName:</strong>
        <%= user.last_name %>
      </p>

    </div>
</div>    
<div class="modal-footer">
    <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
</div>

app/views/users/_user_row.html.erb
 <tr id="UserRow_<%= user.id %>">
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.identifier %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user, data: { bs_toggle: "modal", bs_target: "showUserModal",remote: true } %></td>
        <td><%= link_to 'Edit', edit_user_path(user) data: { bs_toggle: 'modal', bs_target: '#editUserModal', remote: true } %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/users/create.js.erb
<% if @user.errors.any? %>
  alert('Invalid Details');
<% else %>
 $("#usersTable").prepend("<%= escape_javascript render('user_row', user: @user) %>");
 $(".close-modal").click();
<% end %>

app/views/users/destroy.js.erb
$("#userRow_<%= @user.id %>").remove();

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
$('#editUserForm').html("<%= escape_javascript render('form', user: @user) %>")

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<%= link_to "Download as CSV", users_path(format: :csv)%>

<h1>Users</h1>
<%= form_with url: import_users_path, method: :post do |form|  %>
   <%= form.file_field :file , accept: ".csv"%>
   <%= form.button "Import" %>
<% end %>
<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary btn-sm",
 data: { bs_toggle: 'modal', bs_target: '#newUserModal', remote: true }
 %>
 <br><br>

  <table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>UserName</th>
      <th>Email</th>
      <th>Identifier</th>
      <th>FirstName</th>
      <th>LastName</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="usersTable">
    <% @users.each do |user| %>
     <%= render 'user_row', user: user %>
    <% end %>
  </tbody>
</table>
</div>

<br>



<!-- Modal -->
<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="newUserModalLabel">Create New User</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
   <div id="newUserForm">
   </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1" aria-labelledby="editUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editUserModalLabel">Edit User</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
   <div id="editUserForm">
   </div>
    </div>
  </div>
</div>



<div class="modal fade" id="showUserModal" tabindex="-1" aria-labelledby="showUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="editUserModalLabel">Show User Details</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
   <div id="showUserForm">
   </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$('#newUserForm').html("<%= escape_javascript render('form', user: @user) %>")

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>UserName:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @user.identifier %>
</p>

<p>
  <strong>FirstName:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>LastName:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.js.erb
$("#showUserDetails").html("<%= escape_javascript render('show', user: @user) %>")

app/views/users/update.js.erb
<% if @user.errors.any? %>
  alert('Invalid Details');
<% else %>
 $("#userRow_<%= @user.id %>").replaceWith("<%= escape_javascript render('user_row', user: @user) %>");
 $(".close-modal").click();
<% end %>